# Generated by Django 2.2.4 on 2021-06-02 13:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Bdate',
            field=models.DateField(default=datetime.datetime(2021, 6, 2, 16, 15, 42, 896577)),
        ),
    ]
