# Generated by Django 2.2.4 on 2021-06-06 10:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_auto_20210606_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Bdate',
            field=models.DateField(default=datetime.datetime(2021, 6, 6, 13, 52, 13, 884593)),
        ),
    ]
