# Generated by Django 2.2.4 on 2021-06-06 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0004_auto_20210605_2242'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
